### ISSUE TITLE
JavaScript Type Errors for Showing Calculation Progress

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/mongochemdeploy#60]
As of this morning, when I ran `ocdeploy pull` to update all of my docker images, I started running into a problem with viewing the calculation progress. When I use the nwchem notebook, and I run the `show()` commands during a calculation such as `result.orbitals.show(mo='homo', iso=0.005)` or `result.vibrations.show(mode=1)`, nothing appears and an error prints in the javascript console. However, the calculation still runs, and when the calculation is complete, I can still view the results by running the `show()` command again. I just can't view the progress (`Queued`, `Running`, etc.).

I have attached a javascript error log where I made the issue happen. Search for `Uncaught TypeError`, I think that is the first error that occurred when I tried to show the calculation progress.

[errors.log](https://github.com/OpenChemistry/mongochemdeploy/files/2988902/errors.log)

**Comment by psavery** [comment]
@alesgenova

**Comment by cjh1** [comment]
@psavery This should be resolved by pulling the latest openchemistry/jupyterlab container.

**Comment by psavery** [comment]
Indeed, the JavaScript errors do not occur anymore. And the `Pending Calculations` do appear. However, the status does not appear to update (it is always `?` as seen in the picture below). But, the calculations do run, and I can visualize them when they finish.
![Screenshot from 2019-03-20 13-41-53](https://user-images.githubusercontent.com/9558430/54706812-2c883b00-4b16-11e9-88f7-f418175007bc.png)

**Comment by alesgenova** [comment]
@psavery  the notification channel has been unreliable, it might getting closed. If you look into the console, do you notice any error related to this?

**Comment by psavery** [comment]
@alesgenova I'll re-run it and attach the console output.

**Comment by psavery** [comment]
@alesgenova Here is a log where I went through the nwchem notebook steps one by one, up to and including `result.orbitals.show(mo='homo', iso=0.005)`, where the issue occurs.

[output.log](https://github.com/OpenChemistry/mongochemdeploy/files/2989644/output.log)

**Comment by psavery** [comment]
This does not appear to be an issue for me anymore (at least, not when using all master branches). Closing unless it shows up again.
