### ISSUE TITLE
Girder dev mode

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/mongochemdeploy#79]
Currently, the mongochemdeploy girder server starts up in production mode. This is good for beta.openchemistry.org. For developing, however, development mode is preferred so that the girder server will automatically restart when we make changes to the locally mounted mongochemserver repository. Once [this girder PR](https://github.com/girder/girder/pull/3062) gets merged, we should setup `ocdeploy` to use the `--dev` option.

**Comment by brianhelba** [comment]
FYI, you can also make the file `~/.girder/girder.cfg` contain:
```
[server]
mode = "development"
```
to always start the server in development mode.

**Comment by psavery** [comment]
Yeah, our `girder` is in a docker container, and we wanted it to be built in production mode by default, but have the option to start in development mode for developing.

I know we can probably set up something to modify the `~/.girder/girder.cfg` file when we start docker, but the `--dev` option will be a little nicer.

**Comment by psavery** [comment]
Fixed by #81
